export default eventHandler((e) => {
    return [
        {
            "id": 1,
            "title": "Payra2",
            "img": "/img/products/1.jpg",
            "status":"new",
            "discount": "0",
            "price": "14",
            "rating": "11",
            "categorey": "Category Name",
        },
        {
            "id": 2,
            "title": "Payra",
            "img": "/img/products/2.jpg",
            "status":"new",
            "discount": "5",
            "price": "20",
            "rating": "11",
            "categorey": "Category Name",
        },
        {
            "id": 3,
            "title": "Dragon",
            "img": "/img/products/3.jpg",
            "status":"new",
            "discount": "15",
            "price": "140",
            "rating": "11",
            "categorey": "Category Name",
        },
        {
            "id": 4,
            "title": "Badana",
            "img": "/img/products/4.jpg",
            "status":"out of stock",
            "discount": "10",
            "price": "14",
            "rating": "11",
            "categorey": "Category Name",
        },
        {
            "id": 5,
            "title": "Turmuz",
            "img": "/img/products/5.jpg",
            "status":"new",
            "discount": "10",
            "price": "14",
            "rating": "11",
            "categorey": "Category Name",
        },
        {
            "id": 6,
            "title": "Mango",
            "img": "/img/products/6.jpg",
            "status":"new",
            "discount": "25",
            "price": "30",
            "rating": "11",
            "categorey": "Category Name",
        },
        {
            "id": 7,
            "title": "Lusu",
            "img": "/img/products/7.jpg",
            "status":"new",
            "discount": "10",
            "price": "14",
            "rating": "11",
            "categorey": "Category Name",
        },
    ]
})